spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    database: mysql
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true